### ISSUE TITLE
Auth with username and password

### ISSUE THREAD

**Issue by Amialc** [auth0/Auth0.WinformsWPF#14]
When using authentication with connection, username and password
```cs
var user = await auth0.LoginAsync(
    "my-db-connection",     // connection name here
    "username",
    "password");
```
it rises `HttpRequestException` with additional info `Response status code does not indicate success: 401 (Unauthorized).` My app:

![image](https://cloud.githubusercontent.com/assets/1114365/12680351/0834d542-c6b2-11e5-8d00-7da2660764a4.png)

When im using samples provided here, got `UriFormatException` with `Invalid URI: The hostname could not be parsed.`:

![image](https://cloud.githubusercontent.com/assets/1114365/12680720/ff3fd0de-c6b3-11e5-86af-728f329cf038.png)

Different additional info on [WPF sample project](https://github.com/auth0/auth0-winforms-wpf-sample):

![image](https://cloud.githubusercontent.com/assets/1114365/12680480/cc63e3e0-c6b2-11e5-82a3-4460dd0346ab.png)

**Comment by jerriep** [comment]
@Amialc I also just tested this and the first time I got the HTTP Status Code 400 like you did it.

Then I tried to debug it and all of a sudden I am not getting this anymore. Seems like it is an intermittent error perhaps on the Auth0 server side. Can you please test this again and let me know whether you are getting the same error?

**Comment by jerriep** [comment]
The 401 Unauthorized you will get when the username / password combination does not exist on the connection you are specifying.

**Comment by jerriep** [comment]
@Amialc I am closing this for now. If you can reproduce the HTTP 400 please reopen

**Comment by Amialc** [comment]
@jerriep i can't reproduce HTTP 400 error for now, but I'm get 401 Unauthorized even when i'm using correct username/password. I have modified sample to print username:password and i'm sure it is correct.

![image](https://cloud.githubusercontent.com/assets/1114365/12812112/8b6fd7c8-cb39-11e5-8815-1aad05b01209.png)

**Comment by Amialc** [comment]
@jerriep issue still here. When i'm trying to login using twitter or facebook i'm get 401 Unauthorized and this:
![image](https://cloud.githubusercontent.com/assets/1114365/18089455/ba35d976-6ec8-11e6-9d14-5bffb0d08a9b.png)
