### ISSUE TITLE
Refresh Token

### ISSUE THREAD

**Issue by dspear** [auth0/Auth0.WinformsWPF#22]
I have noticed that there is no refresh token available in the current library. jarlef has submitted some changes to make it available. Do you have plans to incorporate those changes, or to provide the token in some other way?

**Comment by jerriep** [comment]
I will look into that one. That PR is very outdated, so I will have to spend some time on getting it working on the current code base. Adding it to my list of tasks.

**Comment by saltukalakus** [comment]
Hi @jerriep is there a progress for this issue?

**Comment by saltukalakus** [comment]
Related issue => ZD-18295

**Comment by jerriep** [comment]
@saltukalakus Sorry, I was away on leave

Can you please look at rather using the Auth0.NET SDK to obtain refresh tokens?

https://github.com/auth0/auth0.net

Specifically look at the `GetDelegationTokenAsync` method of the `AuthenticationApiClient`:
https://github.com/auth0/auth0.net/blob/master/src/Auth0.AuthenticationApi/AuthenticationApiClient.cs#L223

Pass an instance of `RefreshTokenDelegationRequest ` to this method.

More docs on the `/delegation` endpoint can be found at https://auth0.com/docs/api/authentication#delegation

**Comment by jerriep** [comment]
Implemented with 0a3c08db0665c5f0f70e71e7aeb4b43dfc226e47

**Comment by jamesmacfie** [comment]
Not sure if this is the right place to raise this, but with that pre-release version I can't get the login to work when requesting a refresh token. If I remove the refresh token changes it still works fine. The error is a bit cryptic as I can't debug the nuget package.

If it helps, the code I'm using to test this is:

``` c#

auth0.LoginAsync(this, scope: "openid offline_access", withRefreshToken: true, device: "recorder")

```

And the exception message is `{"device parameter must be specified"}` even though I've provided a device name.

![screen shot 2017-02-02 at 2 08 25 pm](https://cloud.githubusercontent.com/assets/1654201/22533173/244d535e-e951-11e6-9c0d-f89d1fa80ce1.png)

Any help would be appreciated :)

**Comment by jerriep** [comment]
Hi James,

I am unable to reproduce. It works 100% fine for me.

Could you please send me your Domain and Client ID which you pass in the constructor for `Auth0Client`, then I can try it with your settings. 

Also make sure that your Client allows me to sign up with a new user or alternatively send me a username/password I can use.

You can send these details to me at jerrie (at) auth0.com

BTW, you do not have to add `offline_access` to the scope. The `withRefreshToken` will automatically do that. Will still work either way, but it is not necessary.
