### ISSUE TITLE
GetRefreshedToken example?

### ISSUE THREAD

**Issue by ritdaw** [auth0/Auth0.WinformsWPF#24]
If using LoginAsync to get a refreshtoken & initial id_token, do we then use GetRefreshedToken to get a new id_token when the original one has expired?

Testing with 9.0.0-beta1.

**Comment by ritdaw** [comment]
Something like the below?
```
auth0.GetRefreshedToken("EXISTING_REFRESH_TOKEN").ContinueWith(t =>
{
	if (t.IsFaulted)
	{
		Console.WriteLine(t.Exception.InnerException.ToString());
	}
	else
	{
	   String idToken = t.Result["id_token"];
	}
},
TaskScheduler.FromCurrentSynchronizationContext());
```

**Comment by jerriep** [comment]
That is correct. Are you experiencing any issues with this?

**Comment by ritdaw** [comment]
No, just wanted to check it is the right way to get a new token.
