### ISSUE TITLE
LoginAsync clears all cookies in IE11

### ISSUE THREAD

**Issue by Valtarr** [auth0/Auth0.WinformsWPF#25]
### Problem:
When using LoginAsync (Auth0Client.cs, line 68) all cookies in IE11 for **all(!)** sites are cleared. (which is unacceptable).
Else cleared auth0 cookies - last login is not saved.
Reproduced on: Windows 8, Windows 10

### Reason:
In WebBrowserHelper.cs there is a ClearCache method (WebBrowserHelper.cs, line 119) called from ShowUI (BrowserAuthenticationForm.cs, line 133) which clears everything.

### Proposition:
Clear cache should be made optional. For that **bool** parameter can be added to next methods:

- **Auth0Client.cs**, **LoginAsync**, line **68**

- **BrowserAuthenticationForm.cs**, **ShowUI**, line **131** (pass value from LoginAsync)

Difference between login with and without clearing cache:
With clearing cache:
![loginclearcache](https://cloud.githubusercontent.com/assets/24985395/22728867/d4eae3de-ede8-11e6-8d44-c3ef9119fc6f.png)
Without clearing cache:
![loginnoclearcache](https://cloud.githubusercontent.com/assets/24985395/22728870/d8cb8508-ede8-11e6-81b6-c73929d5ba6f.png)

**Comment by jerriep** [comment]
I'll look into providing an option for this.

**Comment by jerriep** [comment]
Please grab latest version (0.9.0) from NuGet: https://www.nuget.org/packages/Auth0.WinformsOrWPF/

The `Auth0Client` class now has a property called `ShouldClearBrowserCache`. By default it is set to `true` to preserve existing behaviour. You can set it to `false` to prevent clearing of the browser cache.
