### ISSUE TITLE
No validation for incorrect username

### ISSUE THREAD

**Issue by Valtarr** [auth0/Auth0.WinformsWPF#26]
Incorrect username provokes errors in login widget.
For reproduce type any fake username in login widget, click LOG IN or press Enter.
The result:
![000281](https://cloud.githubusercontent.com/assets/24985395/22751024/98643bb0-ee3b-11e6-8c39-96e2d8731f75.png)

**Comment by jerriep** [comment]
I am unable to reproduce this. I used a normal database connection. What sort of connection(s) have you configured in Auth0?

**Comment by Valtarr** [comment]
We used enterprise login, without database.
Method **LoginAsync** from **Auth0Client.cs**, line **68**.

**Comment by jerriep** [comment]
Which Enterprise Login connection(s) have you configured?

**Comment by Valtarr** [comment]
We use:

- Microsoft Azure AD
- Active Directory / LDAP
- ADFS

**Comment by jerriep** [comment]
OK, I'll set up an environment for this to test this as well as your other
issue related to ADFS. I will only be able to look at this next week though

**Comment by jerriep** [comment]
Hi @Valtarr , apologies for the delay. I am still waiting to get access to our test AD environment in order to try and reproduce this

**Comment by jerriep** [comment]
@Valtarr I configured an AF / LDAP connection and I am unable to reproduce.

A couple of things:

1. It seems that you have defined a custom login page in Auth0. If so, can you please send me the code for your custom login page? You can send it to jerrie (at) auth0.com

2. Can you show me the exact code for your call to `LoginAsync` ?

**Comment by Valtarr** [comment]
Fixed.
In custom login page should be used:
`<script src="https://cdn.auth0.com/js/lock/10.9/lock.min.js"></script>`
