### ISSUE TITLE
Web-page with error is shown in case of authorization of user from ADFS connection

### ISSUE THREAD

**Issue by Valtarr** [auth0/Auth0.WinformsWPF#27]
Web-page with error is shown in case of authorization of user from ADFS connection.

### Steps to reproduce
1. Login as user from ADFS. Security alert is displayed:
![000283](https://cloud.githubusercontent.com/assets/24985395/22751890/fbc1484e-ee3e-11e6-80f1-3cf9da1d4c94.png)
2. Click No

### Actual
Web error inside the desktop window:
![000282](https://cloud.githubusercontent.com/assets/24985395/22751216/5085a184-ee3c-11e6-96fe-1a003239b650.png)

### Expected

- Handle such situation

- Don't show web error inside desktop app

**Comment by jerriep** [comment]
I'll try and see whether I can reproduce

**Comment by jerriep** [comment]
@Valtarr Did changing to the new version of Lock (as discussed over here: https://github.com/auth0/Auth0.WinformsWPF/issues/26) also fix this issue for you?

**Comment by Valtarr** [comment]
@jerriep No. Bug is still reproducible.

**Comment by jerriep** [comment]
@Valtarr Would you mind trying out our new OIDC Client instead:
https://auth0.github.io/auth0-oidc-client-net/

WPF or Windows Forms sample can be found over here:
https://github.com/auth0-community/auth0-WinFormsWPF-oidc-samples/tree/master/00-Starter-Seed

**Comment by Valtarr** [comment]
@jerriep Unfortunately, OIDC client is not working with our Azure AD.
Error: "Error redeeming code: Unauthorized / no description"

**Comment by jerriep** [comment]
Will look into this for you

**Comment by jerriep** [comment]
@Valtarr Apologies for not getting back to you

Can you please ensure that under the Settings for your Client in the Auth0 Dashboard, you have set the **Client Type** to **Native**. Then try the Auth0 OIDC Client again

**Comment by Valtarr** [comment]
@jerriep 
As we discovered - OIDC is not supporting  JsonWebSignatureAlgoritjm HS256 - and we can not switch now to another. That's the problem.

**Comment by jerriep** [comment]
@Valtarr Is there a reason why you cannot create a new Client which uses RS256 and then use that new one?

**Comment by jerriep** [comment]
@Valtarr Is this still an issue for you?

As mentioned before, this library is deprecated, and should not be used anymore

**Comment by jerriep** [comment]
@Valtarr I am closing this issue. Feel free to re-open if this is an issue
