### ISSUE TITLE
Poor input box layout for 'Enter a verification code' using Google 2-step Verification.

### ISSUE THREAD

**Issue by Holf** [auth0/Auth0.WinformsWPF#29]
After failing to authenticate using 'Tap **Yes**' authentication (see #28), I tried using one of the alternative verification methods offered, this being Google sending an SMS to my phone containing a code which I must then enter.

Although this functionality works fine, the layout is off for the code input box, as you can see from the following screenshot:
![image](https://user-images.githubusercontent.com/3245273/27193645-88de55a2-51f7-11e7-914d-8094eedd901e.png)

**Comment by jerriep** [comment]
Unfortunately there is not much we can do about this. This web page is generated by Google and displayed using the Windows WebBrowser control - neither of which we have control over.

**Comment by Holf** [comment]
Hm, tough one! I suppose one could inject some CSS / Styling into the response from Google but it does seem a bit beyond the call of duty to start considering this. :-)

**Comment by jerriep** [comment]
Yeah, this is not something I believe you will have any control over.
