### ISSUE TITLE
Asynchronous login not completed on Cancel

### ISSUE THREAD

**Issue by ta-stott-oe** [auth0/Auth0.WinformsWPF#3]
If you call [`Auth0Client.LoginAsync()`](https://github.com/auth0/Auth0.WinformsWPF/blob/master/Auth0.Windows/Auth0Client.cs#L52) and then click *Cancel* on the login form, the `Task` returned by `LoginAsync()` is never completed.

Shouldn't the `Completed` event be fired [here](https://github.com/auth0/Auth0.WinformsWPF/blob/master/Auth0.Windows/BrowserAuthenticationForm.cs#L152) with a `null` Auth0User?

**Comment by siacomuzzi** [comment]
Good catch, I just included the call to the `Error` event ([details](https://github.com/auth0/Auth0.WinformsWPF/commit/969c67f20bee1e374d02f953f272269143a9f5ad)).

New version is ready @ __Auth0.WinformsOrWPF 0.7.1__

Thanks for reporting!
