### ISSUE TITLE
IdTokenExpiresAt is never populated correctly?

### ISSUE THREAD

**Issue by jngexact** [auth0/Auth0.WinformsWPF#8]
We don't seem to be getting the correct expiry date for the token. In Auth0User, it appears to be initialized by looking for the exp in Profile and it's never there (even though it's been set in our Auth0 portal), defaulting to a MaxValue instead.

Is there something else we need to configure?

**Comment by jerriep** [comment]
Hi @jngexact, you are correct that it is not populated correctly. The thing is however that the `/userinfo` endpoint which returns the user profile is not returning the expiration date of the token. I am not sure whether it ever as, and whether that code ever worked correctly.

But, the token is just a normal JWT, so the quickest way for you to determine what the expiry of a token is, is to use one of the .NET JWT libraries listed at http://jwt.io/

You can for example use https://github.com/dvsekhvalnov/jose-jwt to decode the token and then look the the `exp` value to determine the UNIX datetime value for when the token expires.

Would this work for you?

**Comment by jngexact** [comment]
A bit late, but to follow up: Yes, to get the expiration date, we're decoding the token and extracting the exp. Thanks!
