### ISSUE TITLE
AccessViolationException after second login.

### ISSUE THREAD

**Issue by rizman** [auth0/Auth0.WinformsWPF#9]
Hi,
I'm facing an issue while trying to login using the Auth0.WinformsWPF Library. I'm developing an WPF application and am using a simple Auth0 Database connection.

The application is being developed using the MVVM pattern (MVVM Light Framework)

I tried using a totally bare bones application and the problem persists. Anyway, as you will see in the stacktrace, the problem seems to come from the PInvoke of DeleteUrlCacheEntry

Here is what happens and how I can reproduce the behaviour:
1. User login with: Auth0Client.LoginAsync(string connection, string username, string password) override.
2. User logout with Auth0Client.Lougout()
3. User (same or other user, doesn't matter) login with: Auth0Client.LoginAsync(string connection, string username, string password) override.
4. User logout with Auth0Client.Lougout() ==> throws AccessViolationException with message:
"Attempted to read or write protected memory. This is often an indication that other memory is corrupt."

Here is the call Stack:
   at Auth0.Windows.WebBrowserHelpers.DeleteUrlCacheEntry(IntPtr lpszUrlName)
   at Auth0.Windows.WebBrowserHelpers.ClearCache()
   at Auth0.Windows.Auth0Client.Logout()
   at MyApp.Service.AuthenticationService.LogoutCurrentUser() in C:\Source\Projects\MyApp\MyApp\Service\AuthenticationService.cs:line 69
   at MyApp.ViewModel.LoginViewModel.LogoutCommandExecute() in C:\Source\Projects\MyApp\MyApp\ViewModel\LoginViewModel.cs:line 115

I don't really understand what happens in the ClearCache method and why this is necessary. Just saw that the last commit added the call to ClearCache to the logout method. 

Otherwise, everything seems to work like a charm.

Hope someone knows what happens here?

**Comment by jerriep** [comment]
Thank you for reporting it @rizman. I'll look into it

**Comment by rizman** [comment]
@jerriep Thank you for your quick answer.

**Comment by jerriep** [comment]
@rizman I had to do some code reorganization on this repo, so I also fixed your issue. You can grab latest from Nuget, and let me know if you have any further hassles

**Comment by rizman** [comment]
@jerriep Hi. Just updated to the latest version from NuGet and I haven't had the problem anymore. 

Thanks for your quick reaction :+1:

**Comment by jerriep** [comment]
Pleasure :) Thanks for letting me know
